### PR TITLE
Add log as motion data file type

### PR DESCRIPTION
**Pull request by IamPete1**
To go with https://github.com/AdrianEddy/telemetry-parser/pull/14

I'm not sure if we also need to update the git hash in the Cargo stuff once the telemetry-parer PR is merged?

### CODE REVIEW

**Comment by avsaase** [comment]
What settings do you need in ArduPilot to get this working?

**Comment by IamPete1** [comment]
@avsaase Need to be on the dev branch, 4.2.dev (Copter, Plane or Rover), select `VideoStabilization` in `LOG_BITMASK`. Fly/Drive about then use Mission Planner to convert the `.bin` "dataflash" log to `.log` and use the `.log` in Gyroflow.

**Comment by avsaase** [comment]
> @avsaase Need to be on the dev branch, 4.2.dev (Copter, Plane or Rover), select `VideoStabilization` in `LOG_BITMASK`. Fly/Drive about then use Mission Planner to convert the `.bin` "dataflash" log to `.log` and use the `.log` in Gyroflow.

Does this require increasing the PID loop rate?

**Comment by IamPete1** [comment]
@avsaase no. It is logged at loop rate, so at 400hz on copter by default.

**Comment by avsaase** [comment]
I want to use this on planes which I think by default use lower loop rates so I guess I should increase it. 

Would it be an idea to add some documentation to the gyroflow website on how to set this up?

**Comment by IamPete1** [comment]
@avsaase right, so 50hz on plane, you may want to up the loop rate, but planes are not going to be as noisy as a copter.

**Pull request merged**
