### PR TITLE
Increment values in number field using up/down keys based on cursor position

### PR DESCRIPTION
**Pull request by czukowski**
This changes the behavior of up and down keys in Numeric Fields to work in a similar fashion to DaVinci Resolve. The digit under the cursor position is incremented.

Not sure about `UtilTest.js`, I felt I needed to have the function covered by a test, but I didn't find a good place to put it...

### CODE REVIEW

**Comment by AdrianEddy** [comment]
Could you implement it in Rust instead of JS? Then the test can also be a native Rust test
The reason is that sometime in the future I would want to replace Qt/QML with another GUI framework and that means rewriting all additional logic to Rust anyway. I'm aiming to reduce the amount of logic in the UI layer as much as possible and that function is entirely self-contained and can be easily written in Rust, and will work with any potential GUI framework change in the future. 
ChatGPT should be able to quickly do the JS->Rust conversion for you with little manual intervention

**Comment by AdrianEddy** [comment]
Also, I feel like this function is overly complex, due to the fact that it operates on a string and manually calculating the carry. What if instead it would simply calculate the cursor distance from a decimal point separator and use pow(10, x) or pow(10, -x) to add/subtract for example 0.100 or 0.001 as a number?

**Comment by czukowski** [comment]
> Also, I feel like this function is overly complex, due to the fact that it operates on a string and manually calculating the carry. What if instead it would simply calculate the cursor distance from a decimal point separator and use pow(10, x) or pow(10, -x) to add/subtract for example 0.100 or 0.001 as a number?

I tried that first, but I ran into issues recalculating the cursor position (to keep it in place in the input field) that made the function longer and uglier, so I decided to change it to operate on string. It came out long too but I think is more readable (though I haven't kept it so I can't compare now)...

> Could you implement it in Rust instead of JS? Then the test can also be a native Rust test The reason is that sometime in the future I would want to replace Qt/QML with another GUI framework and that means rewriting all additional logic to Rust anyway. I'm aiming to reduce the amount of logic in the UI layer as much as possible and that function is entirely self-contained and can be easily written in Rust, and will work with any potential GUI framework change in the future. ChatGPT should be able to quickly do the JS->Rust conversion for you with little manual intervention

I'll see what I can do.

**Comment by AdrianEddy** [comment]
> but I ran into issues recalculating the cursor position (to keep it in place in the input field)
Wouldn't that be simply solved by simply finding the point separator again in the new number string?

**Comment by AdrianEddy** [comment]
ChatGPT yielded this, I didn't check it, but I meant something along these lines:
```rust
fn modify_digit(number: f64, cursor_position: usize, increase: bool) -> (f64, usize) {
    // Convert the number to a string to find the decimal point
    let num_str = number.to_string();
    let decimal_pos = num_str.find('.').unwrap_or(num_str.len());

    // Calculate the position difference
    let pos_diff = if cursor_position > decimal_pos {
        cursor_position - decimal_pos - 1
    } else {
        cursor_position - decimal_pos
    };

    // Calculate the value to add or subtract
    let mut modifier = 10f64.powi(pos_diff as i32);
    if cursor_position > decimal_pos {
        modifier = 1.0 / modifier;
    }

    // Modify the number
    let mut new_number = if increase {
        number + modifier
    } else {
        number - modifier
    };

    // Adjust the cursor position if the number of digits has changed
    let new_num_str = new_number.to_string();
    let new_decimal_pos = new_num_str.find('.').unwrap_or(new_num_str.len());
    let mut new_cursor_position = cursor_position;

    if new_decimal_pos != decimal_pos {
        new_cursor_position = if increase {
            cursor_position + 1
        } else {
            cursor_position - 1
        };
    }

    (new_number, new_cursor_position)
}
```

**Comment by czukowski** [comment]
@AdrianEddy I managed to get tests running so far (my progress is slow because I can only put a limited amount of time into this, per day), now only to rewrite the function... 

One issue is that the function needs to accept and return string values from the text fields because sometimes it needs to return values with multiple leading zeros to maintain the cursor position for increments in succession, for example:

```
"|200 [-]" → "|100 [-]" → "|000" [-] → "-|100" [-] → "-|200"
```

Another one is that string values in NumberFields are formatted according to a locale, the decimal separator may be a period or a comma, and there also might be various group separators, so the function needs to be locale-aware (`QLocale`, I guess, but then it's counter-productive if you want to move away from QT) or operate on strings directly like I had in JavaScript (which you say is too complex) or NumberFields should be more restrictive and use a fixed format, eg. with a period and no group separators (which I think, for the purpose of being numeric fields in Gyroflow, would make more sense than using a local format, but I don't know if you'd be open to this). 

Also, when I asked ChatGPT for a function that has a string input, it suggested roughly the same approach as mine in Javascript, with some Rust-specific quirks that kind of make the function shorter, but not necessarily more readable, at least for me...

Any thoughts, which way to go from here?

**Comment by AdrianEddy** [comment]
you can just change the parameter to `num_str` and have the first line as `let number = num_str.parse::<f64>();` and return string as well (`new_num_str`)

if you need to add leading zeros to `new_num_str` (based on new_cursor_position), just left pad it with '0' chars

**Comment by czukowski** [comment]
> you can just change the parameter to `num_str` and have the first line as `let number = num_str.parse::<f64>();` and return string as well (`new_num_str`)
> 
> if you need to add leading zeros to `new_num_str` (based on new_cursor_position), just left pad it with '0' chars

Well, that much is clear, I was more wondering about the locale, when I convert it to a number, the positions of digits and decimal separator may change.

**Comment by AdrianEddy** [comment]
well your original function doesn't deal with locale properly as well.

I think we need to just calculate differences between the decimal point position before and after, and decimal point position in formatted string (in QML) and non-formatted string (in Rust). That function should return a number as f64 (because formatting will be handled in QML with `toLocaleString` and a position offset (instead of new position). This way we avoid formatting the number to string on the Rust side altogether. This should cover all cases and handle all locales properly

**Comment by czukowski** [comment]
> well your original function doesn't deal with locale properly as well.

It kind of does, it just skips all non-digit characters and leaves them in place :)

> I think we need to just calculate differences between the decimal point position before and after, and decimal point position in formatted string (in QML) and non-formatted string (in Rust). That function should return a number as f64 (because formatting will be handled in QML with `toLocaleString` and a position offset (instead of new position). This way we avoid formatting the number to string on the Rust side altogether. This should cover all cases and handle all locales properly

In this case, the cursor position must be also somehow recalculated in the non-formatted string, that was what had put me off from using a float value argument in my previous attempts. 

Why don't we simplify the number format in `NumberField` component so that it doesn't use group separators? Then there should be no need to convert formats, (except perhaps to replace the decimal point character with a period, for a valid float format). Most of numeric fields in Gyroflow don't even accept large enough values, so group separators are probably just an edge case, I only found a couple of fields under Lens profiles. Besides, there are already some numbers printed in the UI with float format and I think it looks absolutely fine.

**Comment by AdrianEddy** [comment]
actually the current code is not using group (thousands) separator at all, so that simplifies things. I also removed one redundant variable there just now

**Comment by czukowski** [comment]
@AdrianEddy I managed to tweak the function in Rust to pass tests - see the TMP commit where it is currently commented out so that I can run tests, however I struggle to connect it to Qt. The compiler complains about return value of the method in the controller (same if I create a struct instead of a tuple). Can you give any pointers?

```
error[E0277]: the trait bound `(std::string::String, usize): qmetaobject::QGadget` is not satisfied
   --> src\controller.rs:229:99
    |
229 |     modify_digit: qt_method!(fn(&self, value: QString, cursor_position: usize, increase: bool) -> (String, usize)),
    |                                                                                                   ^^^^^^^^^^^^^^^ the trait `qmetaobject::QGadget` is not implemented for `(std::string::String, usize)`
    |
    = help: the following other types implement trait `qmetaobject::PropertyType`:
              qmetaobject::QPointer<T>
              RefCell<T>
    = note: required for `(std::string::String, usize)` to implement `QMetaType`
    = note: required for `(std::string::String, usize)` to implement `qmetaobject::PropertyType`
note: required by a bound in `qmetatype_interface_ptr`
   --> C:\Users\czukowski\.cargo\git\checkouts\qmetaobject-rs-be16efb753ea0f8f\59029b9\qmetaobject\src\qmetatype.rs:412:35
    |
412 | pub fn qmetatype_interface_ptr<T: PropertyType>(name: &CStr) -> *const c_void {
    |                                   ^^^^^^^^^^^^ required by this bound in `qmetatype_interface_ptr`
```

**Comment by AdrianEddy** [comment]
Yeah so Qt return types are limited so the easiest trick I use it to just return String - separate the cursor position by `;` and in QML just do modify_digit(....).split(';')

Also, move that function to ui_tools.rs

**Comment by czukowski** [comment]
@AdrianEddy pls review

**Comment by AdrianEddy** [comment]
Looks good to me! Thank you for your effort

**Pull request merged**
