### PR TITLE
Copy Sony rtmd metadata to global metadata

### PR DESCRIPTION
**Pull request by thebabush**
Hi,

love gyroflow and never had any problem using it.

However, since I moved from Windows to Mac, DaVinci has not been able to read timecode from my Sony cameras. I'm using gyroflow with `Preserve other tracks`

This is weird, but following advice on [StackOverflow](https://video.stackexchange.com/questions/17948/ffmpeg-preserve-timecode-when-converting-mp4-to-mov), I was able to manually have ffmpeg create a MOV that DaVinci recognizes.

This PR basically does the same as ffmpeg's `-map_metadata 0:s:2`.

`ffprobe` seems to be happier too:

```
$ ffprobe unpatched.mov
[...]
  Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt2020nc/bt2020/unknown, progressive), 3840x2160, 101633 kb/s, SAR 1:1 DAR 16:9, 24.54 fps, 25 tbr, 25k tbn (default)
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : VideoHandler
        vendor_id       : FFMP
  Stream #0:1[0x2]: Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3]: Data: none (stts / 0x73747473), 1024 kb/s
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : Timed Metadata Media Handler
Unsupported codec with id 0 for input stream 2
```

After the patch:

```
$ ffprobe patched.mov
[...]
  Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt2020nc/bt2020/unknown, progressive), 3840x2160, 101633 kb/s, SAR 1:1 DAR 16:9, 24.54 fps, 25 tbr, 25k tbn (default)
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : VideoHandler
        vendor_id       : FFMP
        timecode        : 00:01:59:01
  Stream #0:1[0x2]: Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3]: Data: none (stts / 0x73747473), 1024 kb/s
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : DataHandler
  Stream #0:3[0x4](eng): Data: none (tmcd / 0x64636D74), 0 kb/s
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : TimeCodeHandler
        timecode        : 00:01:59:01
Unsupported codec with id 0 for input stream 2
Unsupported codec with id 0 for input stream 3
```

I'm using a bit of unsafe code to make the logic fine grained, but it works without the `if` of course.

I don't have enough knowledge of MOV/MP4/containers/etc to know if this is the best fix possible, but it works so I thought I'd open a PR.

Cheers

### CODE REVIEW

**Comment by AdrianEddy** [comment]
Copying stream metadata to global metadata doesn't seem right, can you check if just doing `ost.set_metadata(stream.metadata().to_owned());` makes it work?

**Comment by thebabush** [comment]
This works tho:

```
ffmpeg -i C0859.MP4 -map_metadata:s:0 0:s:2 -c copy asd.mov
```

```
  Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt2020nc/bt2020/arib-std-b67, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 99597 kb/s, 25 fps, 25 tbr, 25k tbn (default)
      Metadata:
        handler_name    : Timed Metadata Media Handler
        vendor_id       : FFMP
        timecode        : 00:01:59:01
      Side data:
        displaymatrix: rotation of 90.00 degrees
  Stream #0:1[0x2]: Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74), 0 kb/s
      Metadata:
        handler_name    : Timed Metadata Media Handler
        timecode        : 00:01:59:01
```

**Comment by thebabush** [comment]
Mystery solved I think.

```
$ ffprobe original.mp4
[...]
  Stream #0:2[0x3](und): Data: none (rtmd / 0x646D7472), 1024 kb/s (default)
      Metadata:
        creation_time   : 2024-06-01T17:17:30.000000Z
        handler_name    : Timed Metadata Media Handler
        timecode        : 00:01:59:01
```

Note, **rtmd**, not **tmcd**.

Now, see: https://github.com/FFmpeg/FFmpeg/blob/d55f5cba7b1fd362beb3b0322c5674016a85e859/libavformat/movenc.c#L7516

```c
        /* +1 tmcd track for each video stream with a timecode */
        for (i = 0; i < s->nb_streams; i++) {
            AVStream *st = s->streams[i];
            AVDictionaryEntry *t = global_tcr;
            if (st->codecpar->codec_type == AVMEDIA_TYPE_VIDEO &&
                (t || (t=av_dict_get(st->metadata, "timecode", NULL, 0)))) {
                AVTimecode tc;
                ret = mov_check_timecode_track(s, &tc, st, t->value);
                if (ret >= 0)
                    mov->nb_meta_tmcd++;
            }
        }
```

Which means, with my second `ffmpeg -i C0859.MP4 -map_metadata:s:0 0:s:2 -c copy asd.mov` I'm setting the `timecode: XXXX` metadata on the video track, which causes the code above to trigger.

Now, I have no idea how/if `rtmd` and `tmcd` relate.

Without further understanding, a better patch would be to look for `timecode` in any stream's metadata, and copying it over to the video stream's metadata.

**Comment by AdrianEddy** [comment]
I'm surprised that the timecode is on rtmd track and not the video track or in global metadata. Does Resolve read the timecode from original properly?

**Comment by thebabush** [comment]
Yes.

**Comment by AdrianEddy** [comment]
Ok, please update the patch and change the `is_rtmd` check to `stream.metadata().contains("timecode") and then only set timecode entry in global metadata

**Comment by thebabush** [comment]
Ok. Just FYI, I just checked and setting `timecode` on the video stream achieves the same.

**Comment by AdrianEddy** [comment]
Also, do this before the `if medium`, it should work regardless of the `preverve_other_tracks`

**Comment by thebabush** [comment]
done

**Comment by AdrianEddy** [comment]
looks good, much better than the original solution. Thanks!

**Comment by thebabush** [comment]
Thank you! Gyroflow is amazing.

**Pull request merged**
