### PR TITLE
Add iPhone Support

### PR DESCRIPTION
**Pull request by latenitefilms**
- Initial commit.
- Added `lib.rs` file.
- Updated `Cargo.toml`.
- Currently doesn't work.

### CODE REVIEW

**Comment by latenitefilms** [comment]
Notes to self....

To build:

- `cargo build --target aarch64-apple-ios --release`

Give install script executable permission:

- `chmod u+x install-deps-ios.sh`

Install dependancies:

- `cd gyroflow/ext && ./install-deps-ios.sh`

Make sure `qmake` is in the `PATH`:

- `source __env-macos.sh`

**Comment by AdrianEddy** [comment]
last should be `source __env-ios.sh`

**Comment by latenitefilms** [comment]
Note to self... this is where I'm currently stuck on:

https://gist.github.com/latenitefilms/d2a74cc990e7d93764aee72df784fcf7

...when trying to execute `cargo build --target aarch64-apple-ios --release`

**Comment by AdrianEddy** [comment]
Ended up without using xcode at all, see latest commit. `just ios install-deps` and then `just ios deploy `

**Pull request closed without merging**
